baseURL = 'http://sravjti.in/sra-board-hardware-design'
languageCode = 'en-us'
title = 'SRA Board Hardware Design'

[markup.goldmark.renderer] 
    unsafe= true
[static]
    staticDir="../documentation"